---
title: "Health and Economic Effects of Weather Events"
author: "Mark Jerome"
date: "January 15, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Synopsis.

Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?

Across the United States, which types of events have the greatest economic consequences?

## Data Processing

This analysis uses data from the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database.  A version of the database containing events starting in the year 1950 and ending in November 2011 was downloaded from [Storm Data](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2).

First, let's read the data into R straight from the bzip2 formatted file.

```{R cache=TRUE}
rawData <- read.csv(bzfile("repdata%2Fdata%2FStormData.csv.bz2"))
```

According to a discussion found in [Database Details](https://www.ncdc.noaa.gov/stormevents/details.jsp), "Due to changes in the data collection and processing procedures over time, there are unique periods of record available depending on the event type."  In particular, different event types have been reported over the years.  Before 1996, only a subset of events were recorded.  Beginning in 1996, all event types were recorded.  This analysis will use only data from 1996 on to ensure all event types are properly represented.

```{R cache=TRUE}
datePOSIX <- strptime(rawData$BGN_DATE, "%m/%d/%Y %H:%M:%S")
year <- as.numeric(format(datePOSIX, "%Y"))
stormData <- subset(rawData, year>=1996)
```

This keeps `r prettyNum(dim(stormData)[1], big.mark=",")` of the original `r prettyNum(dim(rawData)[1], big.mark=",")` events, while discarding `r prettyNum(dim(rawData)[1]-dim(stormData)[1], big.mark=",")`.

### Event types

We will want event types to be character rather than factor.
```{R}
stormData$EVTYPE <- as.character(stormData$EVTYPE)
```

The discussion in [Database Details](https://www.ncdc.noaa.gov/stormevents/details.jsp) indicates "48 event types are recorded as defined in NWS Directive 10-1605."  How many event types are found in our data?

```{R}
length(unique(stormData$EVTYPE))
```
That's quite a discrepancy.
Let's make sure capitalization is consistent across recorded event types.
```{R}
stormData$EVTYPE <- tolower(stormData$EVTYPE)
length(unique(stormData$EVTYPE))
```
That's a little better.

What if we ignore event types that contribute less than 1% of the total number of events?
```{R}
eventCounts <- table(stormData$EVTYPE)
eventCountsSorted <- eventCounts[order(eventCounts, decreasing=TRUE)]
eventCumCount <- cumsum(eventCountsSorted)
p99 <- .99 * length(stormData$EVTYPE)
which.max(eventCumCount > p99)
```



## Results

